# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920b0329464857b3f330f97c996f18f34ae765364b302f9d37012ed1f09f26db883ad59444004361a21a67462721dca37427446294c2b367799d1fecbdca4e1b

test:
  secret_key_base: 9295865c50522b08c33a520f5db8c9aaddb6b85edd28b20dcca12c535214340b9d7373a139e92f7770ebbc358165c9bc0c1f2c0470c828b3ad96a57bcbf2f5ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
